### ISSUE TITLE
Add env var to set user/group for PHP process

### ISSUE THREAD

**Issue by cbeier** [wodby/php#12]
If docker is used under a Windows Host with volumes, all files/directories inside the shared volumes are owned by "root" with the permission 0755. Currently, there is no way to change this behaviour or user (see https://github.com/docker/for-win/issues/497#issuecomment-279733590).

But the php process in the container runs with the default user/group "www-data". Basically it works, but if the webserver tries to save a file (e.g. a file upload) there is an access denied error. Because, only root is allowed to store files.

So, all Windows users need a solution to run the php process as root. See https://github.com/wodby/docker4drupal/issues/29#issuecomment-277553889

I think the best way to archive this is, to define new env vars for user and group. The Windows user can then set in his docker-compose the necessary user/group.

Example docker-compose.yml:

```
php:
  image: wodby/drupal-php:7.0-3.0.0
  environment:
    PHP_FPM_USER: root
    PHP_FPM_GROUP: root
  command: php-fpm --allow-to-run-as-root
```

New env vars:
  * PHP_FPM_USER
  * PHP_FPM_GROUP

**Comment by csandanov** [comment]
We [change ownership](https://github.com/wodby/php/blob/master/7.1/docker-entrypoint.sh#L78) of `/var/www/html` volume in the entrypoint to `www-data`. Perhaps you're using different volumes?

**Comment by cbeier** [comment]
Changing ownership or permission (chown / chmod) have no effect inside container on a Windows host. The owner always remains root.

```
php:
    image: wodby/drupal-php:7.0-3.0.0
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - ../src/:/var/www/html
```

![unbenannt](https://user-images.githubusercontent.com/53869/32328538-8e554724-bfda-11e7-816d-1e4174a5b5da.PNG)
