### ISSUE TITLE
Xdebug is enabled by default

### ISSUE THREAD

**Issue by yasenivanovffw** [wodby/php#166]
I am using the GitHub CI to build and validate Drupal website and part of my workflow looks like this:

```
jobs:
  full:
    name: Full (Build, Validate, Test, Deploy)
    runs-on: [self-hosted]
    container:
      image: wodby/drupal-php:8.0
      options: --user root
```
As you see, I don't pass any env variables and according to the [docs](https://github.com/wodby/php#xdebug), xDebug and XHProf should not be loaded, although if I add the following step, it shows xdebug is loaded:

```
 - name: Check if XDebug disabled
   run: php -m
```

Already checked the comments under https://github.com/wodby/php/issues/58, but it didn't help. Is there anything that I am missing?
