### ISSUE TITLE
XDebug broken on linux after chage to host.docker.internal

### ISSUE THREAD

**Issue by Holo96** [wodby/php#197]
[Issue](https://github.com/wodby/php/issues/192) broke linux.

Tested on Docker Engine 26.1.3

host.docker.internal does not work automatically on Linux. You need to add --add-host=host.docker.internal:host-gateway manually. As mentioned [here](https://stackoverflow.com/questions/48546124/what-is-the-linux-equivalent-of-host-docker-internal#answer-62431165).

Proposed solutions:
1. **Revert back to 172.17.0.1**
2. **Add extra_hosts to php container:** as mentioned [here](https://stackoverflow.com/questions/48546124/what-is-the-linux-equivalent-of-host-docker-internal#answer-67158212)
```yml
services:
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
3. Override php env variable for linux: PHP_XDEBUG_CLIENT_HOST
```yml
services:
  php:
    environment:
       PHP_XDEBUG_CLIENT_HOST: 172.17.0.1
```

Edit:
I am using docker4drupal stack, and it does not work out of box.
