### ISSUE TITLE
Do not use www-data as default user

### ISSUE THREAD

**Issue by csandanov** [wodby/php#22]
1. In version 2.x of this image we had `root` as the default user
2. Quickly we realized that it's not good (drush and composer don't like to be run from root) and changed it to `www-data`. User `www-data` (uid/gid 82) is a de-facto standard in Alpine Linux for php-fpm, nginx, apache packages, something similar to `www-data` in Debian/Ubuntu
3. PR https://github.com/wodby/php/pull/18 was posted making a good point that fpm and HTTP server shouldn't have write access to user's files (codebase), as the result we changed fpm user to `php-fpm` (1000) in [3.5.0](https://github.com/wodby/php/releases/tag/3.5.0)
4. Now, we realized that the way we use `www-data` is completely wrong, it's a standard system user that comes with a "package" similar to `www-data` in Debian/Ubuntu that should be used only to run a package daemon, so it's not a usual Linux user and should not be used to log in and manage files
5. Based on 4 we decided to release 4.x version of stack where we add a new default user `wodby` with uid/gid `1000` to match user in most Linux distributions. PHP-FPM will run via sudo with FPM user/group set to `www-data` (82). User `www-data` will be a part of `wodby` group which means your default codebase files should be `644` or `755` (only read access for fpm). If you want to give fpm write access, you should change permissions to `664` or `775`

**Comment by csandanov** [comment]
Also, we now have `nginx` and `apache` as default users in HTTP servers with UID/GID different from `82` and with only read access.

**Comment by Proteo** [comment]
Hi there. Many thanks for your hard work, this is a definitively a great step forward. Don't know if I'm asking too much, but do you think that could be possible to set the wodby uid/gid using variables on container basis, in a future version? In our shop we've adopted your images as base for pretty much everything we do with Drupal and Wordpress, but we use a mixture of host machines (mostly Macs and some flavors of Linux) for local development so having the ability to set custom ids would be insanely great.

**Comment by csandanov** [comment]
@Proteo do you want to have docker build arguments for that? are you going to rebuild the image? 

What kind of issues do you experience with non-matching uid/gid?

**Comment by Proteo** [comment]
Hi @csandanov, we're actually using slightly modified versions of your repos to build customized images to match a specfic `uid:gid` using build arguments. For example, in Mac we use `501:20` since usually that's the `uid:gid` of the user running Docker. I know that you can add your user to the group 82 (_clamav in macOS) as suggested in the docker4drupal documentation, but having a matching uid makes things way easier for everybody.
But the perfect, ideal scenario, would be having the ability to set `uid:gid` _**per container**_, maybe using something [like this](https://github.com/schmidigital/permission-fix/) which basically takes input from ENV variables set in your docker compose file or run arguments. We actually tried to do something like that, hooking some bash commands in your `/bin/init_volumes script` but we soon realized that there are several config directories that need to be taken care of, so simply changing the uid of the user creates access problems in these directories.

**Comment by csandanov** [comment]
I guess we could add a macos image variant with 501:20 for uid/gid. But what kind of issues do you have with non-matching uid/gid in your local environment?

**Comment by Proteo** [comment]
Well, one of the most common and recurring issues is with with D7 projects (yes, we still pretty much live in the D7 realm) where you don't really have a standard process to add new code or even update the existing one. So peeps keep throwing files and never remember to update/change file permissions. But, from your response I assume that setting uid/gid per container is not a feasible thing?

**Comment by csandanov** [comment]
The solution with updating uid/gid is not feasible because you have to be root to perform any manipulation with `wodby` user, this means the default user will be `root`. You can't change your current user id via sudo and stay sane. 

Could you please clarify why do you need to change file permissions for new code? You probably add it from the host machine via git or copying, why would you need to change it? It's still have read permissions for php-fpm so it shouldn't be a problem.

**Comment by csandanov** [comment]
`-dev-macos` variants have been added with default wodby uid/gid 501:20 since `-4.2.0` stability tag. Also, you can now use build arguments `WODBY_USER_ID`/`WODBY_GROUP_ID` to customize ids.

**Comment by Proteo** [comment]
@csandanov absolutely fantastic, thank you very much. You're right, adding code with a different uid is no a major issue because it still can be read. It's more like the purpose of having the 1000 uid matching the user in Linux.
Your support is greatly appreciated, now we have a few less repos to mantain :)

**Comment by johandenhollander** [comment]
@csandanov How should I use the build arguments in a docker-compose file?

Would be nice if rebuilding this image would always take the users uid as a variable.
Some of my coworkers had their systems set up by the sys admin. So the Admin account is then 501 and the user account has 502

**Comment by csandanov** [comment]
@johandenhollander see https://github.com/wodby/php#build-arguments

**Comment by johandenhollander** [comment]
My php section looks like this.
How would I rewrite it to include the build arguments?
Sorry if this is a n00b question... I have no experience with build arguments.
I did try something by adding a dockerfile but that was not successful for me.

```
services:

  php:
    image: wodby/drupal-php:${PHP_WODBY_TAG}
    environment:
      PHP_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.test:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_ENABLED: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 0
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      PHP_MAX_INPUT_VARS: 15000
      PHP_MEMORY_LIMIT: 2048M
      PHP_MAX_EXECUTION_TIME: 360
    volumes:
      - docker-sync:/var/www/html:nocopy
    links:
      - solr
    external_links:
      - mysql
      - dockerdns
    networks:
      - default
      - commonapps_default
    dns:
     - ${DOCKERDNS}
```
