### ISSUE TITLE
docker-entrypoint.sh: line 96: exec_init_scripts: command not found

### ISSUE THREAD

**Issue by jorgetutor** [wodby/php#29]
After running `docker-compose up php `

I get `docker-entrypoint.sh: line 96: exec_init_scripts: command not found`

This is the docker-compose file:

```
version: "2.0"
services:
  php:
    build:
      context: https://github.com/wodby/php.git#:7
      args:
        - FROM_TAG=7.1.14
        - WODBY_USER_ID=107
        - WODBY_GROUP_ID=111
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
      - ./:/var/www/html
```

What am I doing wrong?
Thanks!
