### ISSUE TITLE
How to rebuild image with different uid/gid?

### ISSUE THREAD

**Issue by NikolayShapovalovMoto** [wodby/php#36]
How to rebuild image with docker-composer.yml?

docker-compose.yml
```
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      WODBY_USER_ID: 1002
      WODBY_GROUP_ID: 1002
```
.env
```
# Linux (uid 1000 gid 1000)

WODBY_USER_ID=1002
WODBY_GROUP_ID=1002

#PHP_TAG=7.1-dev-4.6.0
#PHP_TAG=7.2-dev-4.6.0
#PHP_TAG=7.0-dev-4.6.0
PHP_TAG=5.6-dev-4.6.0
#PHP_TAG=5.3-dev-4.6.0
```
