### ISSUE TITLE
XDebug remains always enabled

### ISSUE THREAD

**Issue by subhojit777** [wodby/php#58]
I am using the tag `wodby/drupal-php:7.1-dev-4.2.2`. A portion of `docker-compose.yml` looks like:

```yml
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_XDEBUG: $PHP_XDEBUG_ENABLED
    volumes:
      - ./:/var/www/html
```

`PHP_XDEBUG_ENABLED` is set to 0. However, the container is started with `xdebug` enabled.

I am using this stack inside our CI. We need `xdebug` disabled when Drupal is installed, but need it enabled while running the tests, for code coverage. Therefore, we are controlling it using a `PHP_XDEBUG_ENABLED` shell variable.

What would be the best way to handle this situation?
